### PR TITLE
beautify component style

### PR DESCRIPTION
**Pull request by mzgnr**

### CODE REVIEW

**Comment by Szeliga** [comment]
Would you mind fixing the merge conflict? (it has to do with whitespaces inside curly braces from #5)

**Comment by mzgnr** [comment]
sure :)

**Comment by mzgnr** [comment]
actually i was considering about including redux snippets also ? What is your opinion about that ?

**Comment by Szeliga** [comment]
We would want to keep this package about React only. Redux deserves a separate package.

**Comment by Szeliga** [comment]
@mzgnr Any info on the merge conflicts, or can I close this?

**Comment by mzgnr** [comment]
@Szeliga sorry. I was busy lately. I'll fix it as soon as possible 👍

**Comment by mzgnr** [comment]
new pull request is coming :)

**Pull request closed without merging**
